name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Print Docker Compose file
      run: cat docker-compose.yml

    - name: Docker Compose Up and Build
      run: docker-compose up -d --build

    - name: Print Docker containers
      run: docker ps -a

    - name: Run Tests
      run: |
        python manage.py test