version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080

    volumes:
      - .:/usr/src/app/
    # expose: -- test
    #   - 8000
    ports:
      - 8080:8080
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
