version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn NoWaste.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13.1-alpine
    ports:
      - nowaste:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gen
      - POSTGRES_PASSWORD=gen39nowaste
      - POSTGRES_DB=nowaste

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume: