version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/app/
    # expose: -- test
    #   - 8000
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
