# Generated by Django 4.1.7 on 2023-10-19 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Client')], default='SERVER', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
