# Generated by Django 4.1.7 on 2023-11-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem2",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Restaurant.order2"
            ),
        ),
    ]
