# Generated by Django 4.1.7 on 2023-10-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_pic2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
