# Generated by Django 4.1.7 on 2023-10-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = []
