# Generated by Django 4.1.7 on 2023-10-19 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurantmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='myauthor',
            name='name',
            field=models.CharField(default='User', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_establishment',
            field=models.DateField(default=datetime.date(2023, 10, 19)),
        ),
    ]
