# Generated by Django 4.1.7 on 2023-11-16 17:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "password",
                    models.CharField(
                        max_length=528,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="date_of_establishment",
            field=models.DateField(default=datetime.date(2023, 11, 16)),
        ),
    ]
