# Generated by Django 4.1.7 on 2023-11-01 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_restaurant_date_of_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauthor',
            name='password',
            field=models.CharField(max_length=528, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
