# Generated by Django 4.1.7 on 2023-10-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_auto_20231019_1253"),
    ]

    operations = []
