# Generated by Django 4.1.7 on 2023-11-17 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_tempmanager_alter_restaurant_date_of_establishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempmanager",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="date_of_establishment",
            field=models.DateField(default=datetime.date(2023, 11, 17)),
        ),
    ]
