# Generated by Django 4.1.7 on 2023-10-27 18:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_remove_customer_name_remove_restaurantmanager_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myauthor",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="date_of_establishment",
            field=models.DateField(default=datetime.date(2023, 10, 27)),
        ),
    ]
